- fail:
    msg: "Make sure we've authenticated to the cluster before running this role"
  when: k8s_auth_results.k8s_auth.api_key is not defined

- name: Deploy infra machine config pool
  k8s:
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    state: present
    resource_definition: "{{ lookup('template', 'mcp.yaml.j2') }}"
    validate_certs: no

#- name: output to file
#  template: src=/storage/repos/ocp-day2/roles/infranodes/templates/infra-machineset.yaml.j2 dest=~/output.txt

- name: Deploy infra machine set
  k8s:
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    state: present
    resource_definition: "{{ lookup('template', 'infra-machineset.yaml.j2') }}"
    validate_certs: no

- name: verify node deployment
  vars:
    go_template: !unsafe '{{.status.readyReplicas}}'
  command: "oc get machineset {{ openshift_unique_cluster_name }}-{{ infranodes_name }}
     -n openshift-machine-api
     -o go-template='{{ go_template }}'
     --token {{ k8s_auth_results.k8s_auth.api_key }}
     --insecure-skip-tls-verify=true
     --server=https://api.{{ cluster_name }}.{{ openshift_base_domain }}:6443"
  register: infranodes_verify_result
  until: infranodes_verify_result.stdout.find("{{ infranodes_replicas }}") != -1
  retries: "{{ num_retries }}"
  delay: "{{ num_delay }}"
  changed_when: false
