- name: Deploy openshift rbac configuration
  import_tasks: deploy.yml
  when: apply | default(false)

- name: Teardown openshift rbac configuration
  import_tasks: teardown.yml
  when: teardown | default(false)
  
