apiVersion: v1
kind: Template
metadata:
  name: chrony
objects:
- apiVersion: machineconfiguration.openshift.io/v1
  kind: MachineConfig
  metadata:
    name: "master-chrony-configuration"
    labels:
      machineconfiguration.openshift.io/role: master
  spec:
    config:
      ignition:
        config: {}
        security:
          tls: {}
        timeouts: {}
        version: 2.2.0
      storage:
        files:
        - contents:
            source: "data:text/plain;charset=utf-8;base64,{{ lookup('template', 'chrony.conf.j2') | b64encode }}"
          filesystem: root
          mode: 420
          overwrite: true
          path: /etc/chrony.conf
parameters:
- description: First NTP Server
  name: FIRST_NTP_SERVER
  valueFrom:
    configMapKeyRef:
      name: chrony-config
      key: FIRST_NTP_SERVER
- description: Second NTP Server
  name: SECOND_NTP_SERVER
  valueFrom:
    configMapKeyRef:
      name: chrony-config
      key: SECOND_NTP_SERVER




  chrony.conf: |-
    # Use custom NTP servers
    server FIRST_NTP_SERVER iburst
    server SECOND_NTP_SERVER iburst
    
    # Use public servers from the pool.ntp.org project.
    # Please consider joining the pool (http://www.pool.ntp.org/join.html).
    #pool 2.rhel.pool.ntp.org iburst
    
    # Record the rate at which the system clock gains/losses time.
    driftfile /var/lib/chrony/drift
    
    # Allow the system clock to be stepped in the first three updates
    # if its offset is larger than 1 second.
    makestep 1.0 3
    
    # Enable kernel synchronization of the real-time clock (RTC).
    rtcsync
    
    # Enable hardware timestamping on all interfaces that support it.
    #hwtimestamp *
    
    # Increase the minimum number of selectable sources required to adjust
    # the system clock.
    #minsources 2
    
    # Allow NTP client access from local network.
    #allow 192.168.0.0/16
    
    # Serve time even if not synchronized to a time source.
    #local stratum 10
    
    # Specify file containing keys for NTP authentication.
    keyfile /etc/chrony.keys
    
    # Get TAI-UTC offset and leap seconds from the system tz database.
    leapsectz right/UTC
    
    # Specify directory for log files.
    logdir /var/log/chrony
    
    # Select which information is logged.
    #log measurements statistics tracking
