apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- chrony.yaml
configMapGenerator:
- name: chrony-config
  literals:
    - FIRST_NTP_SERVER: first_base_ntp
      SECOND_NTP_SERVER: second_base_ntp
