apiVersion: v1
kind: Pod
metadata:
  name: base-pod
  namespace: default
spec:
  containers:
    - name: base-container
      ports:
        - $patch: replace
        - containerPort: 8081
        - containerPort: 8082
