apiVersion: v1
kind: List
items:

- kind: CronJob
  apiVersion: batch/v1beta1
  metadata:
    name: cronjob-prune-resources-builds
    namespace: "{{ operation_namespace }}"
  spec:
    schedule: "*/10 * * * *"
    concurrencyPolicy: Forbid
    successfulJobsHistoryLimit: 5
    failedJobsHistoryLimit: 5
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - name: cronjob-prune-resources-builds
              image: registry.redhat.io/openshift4/ose-cli:latest
              command:
              - "/bin/bash"
              - "-c"
              - "oc adm prune builds
                --keep-complete=5
                --keep-failed=2
                --keep-younger-than=240h
                --orphans=true
                --confirm"
            restartPolicy: OnFailure
            terminationGracePeriodSeconds: 30
            activeDeadlineSeconds: 500
            dnsPolicy: ClusterFirst
            serviceAccountName: build-pruner

- kind: ClusterRole
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: build-pruner
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
  rules:
  - apiGroups:
    - ""
    - build.openshift.io
    resources:
    - buildconfigs
    verbs:
    - get
    - list
  - apiGroups:
    - ""
    - build.openshift.io
    resources:
    - builds
    verbs:
    - get
    - list
    - delete

- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: build-pruners
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: build-pruner
  subjects:
  - kind: ServiceAccount
    name: build-pruner
    namespace: "{{ operation_namespace }}"

# ServiceAccount
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: build-pruner
    namespace: "{{ operation_namespace }}"
