kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  annotations:
    description: base-description
  name: vsphere-storage
parameters:
  datastore: base-datastore
  diskformat: thin
provisioner: kubernetes.io/vsphere-volume
reclaimPolicy: base-reclaimpolicy
volumeBindingMode: Immediate
