- name: Deploy image registry config
  import_tasks: deploy.yml
  when: not teardown | default(false)

- name: Teardown image registry config
  import_tasks: teardown.yml
  when: teardown | default(false)