- name: Deploy Monitoring Configuration
  import_tasks: deploy.yml
  when: not teardown | default(false)

- name: Teardown Monitoring Configuration
  import_tasks: teardown.yml
  when: teardown | default(false)
