- name: Deploy openshift custom certs configuration
  import_tasks: deploy.yml
  when: apply | default(false)

- name: Teardown openshift custom certs configuration
  import_tasks: teardown.yml
  when: teardown | default(false)
  
