- fail:
    msg: "Make sure we've authenticated to the cluster before running this role"
  when: k8s_auth_results.k8s_auth.api_key is not defined

- name: Remove custom certs
  k8s:
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    validate_certs: no
    state: absent
    api_version: v1
    kind: Secret
    name: "{{ item[0].name }}"
    namespace: "{{ item[1] }}"
  with_subelements:
    - "{{ tls_certs }}"
    - namespaces
