apiVersion: v1
kind: Pod
metadata:
  name: base-pod
  namespace: default
spec:
  containers:
    - $patch: replace
    - name: nonprod-container
      ports:
        - $patch: replace
        - containerPort: 8081
