- fail:
    msg: "Make sure we've authenticated to the cluster before running this role"
  when: k8s_auth_results.k8s_auth.api_key is not defined

- name: Create elasticsearch operator namespace
  k8s:
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    name: openshift-operators-redhat
    api_version: v1
    kind: Namespace
    validate_certs: no

- name: Create openshift-logging namespace
  k8s:
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    validate_certs: no
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        annotations:
          # Set the default selector so fluentd can be scheduled on all hosts
          # The other components get their labels specifically
          openshift.io/node-selector: kubernetes.io/os=linux
        name: openshift-logging

- name: Create operatorgroup and subscription
  k8s:
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    state: present
    resource_definition: "{{ lookup('template', 'operatorgroup.yaml.j2') }}"
    validate_certs: no

- name: Ensure ClusterLogging crd exists before using it
  shell: >-
    oc
    get crd clusterloggings.logging.openshift.io
    -n openshift-logging
    --token {{ k8s_auth_results.k8s_auth.api_key }}
    --insecure-skip-tls-verify=true
    --server=https://api.{{ cluster_name }}.{{ openshift_base_domain }}:6443
  register: crds
  retries: "{{ num_retries }}"
  delay: "{{ num_delay }}"
  until: '"clusterloggings.logging.openshift.io" in crds.stdout'
  changed_when: false

- name: Create clusterlogging custom resource definition
  k8s:
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    state: present
    resource_definition: "{{ lookup('template', 'clusterlogging-instance.yaml.j2') }}"
    validate_certs: no

- name: Change clusterlogging installplanapproval 
  shell: >-
    oc
    patch subscription/cluster-logging 
    --type=json 
    -p='[{"op": replace,"path":"/spec/installPlanApproval","value":"{{ logging_approval_strategy }}"}]'
    -n openshift-logging
    --token {{ k8s_auth_results.k8s_auth.api_key }}
    --insecure-skip-tls-verify=true
    --server=https://api.{{ cluster_name }}.{{ openshift_base_domain }}:6443

- name: Change elasticsearch installplanapproval
  shell: >-
    oc
    patch subscription/elasticsearch-operator
    --type=json 
    -p='[{"op": replace,"path":"/spec/installPlanApproval","value":"{{ logging_approval_strategy }}"}]'
    -n openshift-operators-redhat
    --token {{ k8s_auth_results.k8s_auth.api_key }}  
    --insecure-skip-tls-verify=true
    --server=https://api.{{ cluster_name }}.{{ openshift_base_domain }}:6443
