- name: Get OpenShift Version
  command: "oc version 
            -o json 
            --token {{ k8s_auth_results.k8s_auth.api_key }}
            --insecure-skip-tls-verify=true
            --server=https://api.{{ cluster_name }}.ral.clinicaldevelopment.ibm.com:6443"
  register: reg_oc_version
  changed_when: false

- name: register ocp_version fact
  set_fact:
    ocp_version: "{{ (reg_oc_version.stdout | from_json).openshiftVersion }}"

- name: register ocp_major_version fact
  set_fact:
    ocp_major_version: "{{ ocp_version.split('.')[:2] | join('.') }}"
  vars:
    ocp_version: "{{ (reg_oc_version.stdout | from_json).openshiftVersion }}"
