- name: Deploy additional nic config
  import_tasks: deploy.yml
  when: not teardown | default(false)

- name: Teardown additional nic config
  import_tasks: teardown.yml
  when: teardown | default(false)
