- name: Deploy default project template
  import_tasks: deploy.yml
  when: not teardown | default(false)

- name: Teardown default project template
  import_tasks: teardown.yml
  when: teardown | default(false)