  tlsSecurityProfile:
    type: Custom
    custom:
      ciphers:
        - ECDHE-RSA-AES128-GCM-SHA256
        - ECDHE-ECDSA-AES128-GCM-SHA256
        - ECDHE-RSA-AES256-GCM-SHA384
        - ECDHE-ECDSA-AES256-GCM-SHA384
        - ECDHE-RSA-CHACHA20-POLY1305
        - ECDHE-ECDSA-CHACHA20-POLY1305
        - AES128-GCM-SHA256
        - AES256-GCM-SHA384
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_128_CCM_8_SHA256
        - TLS_AES_128_CCM_SHA25
      minTLSVersion: VersionTLS12
