apiVersion: v1
kind: List
items:

- apiVersion: v1
  kind: Secret
  metadata:
    name: ibmcloud-toolchain-5edd4b4c-cf75-49eb-b06a-1dc3a7f84f09-us.icr.io
    namespace: default
  type: kubernetes.io/dockerconfigjson
  data:
    .dockerconfigjson: eyJhdXRocyI6eyJ1cy5pY3IuaW8iOnsidXNlcm5hbWUiOiJpYW1hcGlrZXkiLCJwYXNzd29yZCI6ImhDLVpsMnRqZVJxSWlJUXYtc3gxS0xKaExRZFdxNWRvUEFORW4yNksyVmpUIiwiZW1haWwiOiJhQGIuY29tIiwiYXV0aCI6ImFXRnRZWEJwYTJWNU9taERMVnBzTW5ScVpWSnhTV2xKVVhZdGMzZ3hTMHhLYUV4UlpGZHhOV1J2VUVGT1JXNHlOa3N5Vm1wVSJ9fX0=
