- name: verify api DNS
  debug:
    msg="{{ lookup('dig', 'api.{{ cluster_name }}.{{ openshift_base_domain }}')}}"
  register: api_dns_result

- name: fail if api VIP not found
  fail:
    msg: "API VIP not found in DNS"
  when: "api_vip not in api_dns_result.msg"

- name: verify ingress DNS
  debug:
    msg="{{ lookup('dig', 'foo.apps.{{ cluster_name }}.{{ openshift_base_domain }}')}}"
  register: ingress_dns_result

- name: fail if ingress VIP not found
  fail:
    msg: "INGRESS VIP not found in DNS"
  when: "ingress_vip not in ingress_dns_result.msg"

- name: create install dir
  file:
    path: "{{ install_path }}/install-dir"
    state: directory
    recurse: true

- name: Create install-config.yml
  template:
    src: install-config.j2
    dest: "{{ install_path }}/install-dir/install-config.yaml"
    mode: 0666
